<a href="https://colab.research.google.com/github/EspecializacionIA1/Fundamentos_programacion_IA/blob/main/Esfera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%%writefile G10_ProfundidadFunciones.py
import numpy as np

def generarMatriz(N, M):
    # Creamos una matriz de puros ceros de tamaño N x M
    # np.zeros es una de las clases de numPy explciada en la última clase de fundamentos de programación.
    matriz = np.zeros((N, M), dtype=int)

    # Rellenamos solo el interior (no los bordes) con números entre 20 y 120
    """
    Los dos siguientes dos for anidados simplemente recorren fila por fila, columna por columna solo el interior:

        i=1, j=1 → matriz[1][1]
        i=1, j=2 → matriz[1][2]
        i=1, j=3 → matriz[1][3]
        ...
        i=2, j=1 → matriz[2][1]
        ...y así hasta llegar al último interior
    """
    for i in range(1, N-1):
        for j in range(1, M-1):
            matriz[i][j] = np.random.randint(20, 121)

    return matriz


"""El siguiente código es solo para efectos de la pryueba con los
ejemplos dadas en el enunciado del ejercicio. no es parte de la función final.
"""
# def generarMatriz(N, M):
#     matriz = np.array([
#         [ 0,  0,  0,  0,  0,  0],
#         [ 0, 20, 16, 14, 15,  0],
#         [ 0, 15, 13, 12, 14,  0],
#         [ 0, 15, 11, 12, 15,  0],
#         [ 0, 14, 18, 20, 25,  0],
#         [ 0,  0,  0,  0,  0,  0]
#     ])
#     return matriz

def caminoProfundidades(matriz, N, M, a, b):
    camino = [[a, b]]   # lista con las posiciones por donde pasa la esfera
    fila_actual = a
    col_actual = b

    while True:
        """
        Guardamos la profundidad y posición del mejor vecino encontrado hasta ahora
        Al inicio, y el "mejor" somos nosotros mismos
        """
        profundidad_mayor = matriz[fila_actual][col_actual]
        fila_mejor_vecino = fila_actual
        col_mejor_vecino = col_actual

        """
        Revisamos los 8 vecinos usando saltos de -1, 0 y +1
        salto_fila = -1 significa "una fila arriba"
        salto_fila =  0 significa "misma fila"
        salto_fila = +1 significa "una fila abajo"
        lo mismo aplica para salto_col pero en columnas
        """
        for salto_fila in [-1, 0, 1]:
            for salto_col in [-1, 0, 1]:

                # Saltamos el caso donde ambos son 0, porque eso somos nosotros mismos
                if salto_fila == 0 and salto_col == 0:
                    continue

                # Calculamos la posición del vecino
                fila_vecino = fila_actual + salto_fila
                col_vecino = col_actual + salto_col

                # Si ese vecino es más profundo que el mejor que encontramos, lo guardamos
                if matriz[fila_vecino][col_vecino] > profundidad_mayor:
                    profundidad_mayor = matriz[fila_vecino][col_vecino]
                    fila_mejor_vecino = fila_vecino
                    col_mejor_vecino = col_vecino

        """
        Si el mejor vecino sigue siendo nuestra posición actual,
        significa que nadie alrededor es más profundo y la esfera se detiene
        """
        if fila_mejor_vecino == fila_actual and col_mejor_vecino == col_actual:
            break

        # Nos movemos al vecino más profundo
        fila_actual = fila_mejor_vecino
        col_actual = col_mejor_vecino
        camino.append([fila_actual, col_actual])

    return camino

Writing G10_ProfundidadFunciones.py


In [3]:
%%writefile G10_ProfundidadPrincipal.py
from G10_ProfundidadFunciones import generarMatriz, caminoProfundidades

# Pedimos N y M al usuario tal como dice en el enuncuado del ejercicio
N = int(input("Ingresa el número de filas N (6-10): "))
M = int(input("Ingresa el número de columnas M (6-10): "))

# Generamos la matriz
matriz = generarMatriz(N, M)

# Imprimimos la matriz fila por fila
print("\nMatriz generada:")
for fila in matriz:
    print(fila)

# de acuerdo a lo que nos pide el ejercicio, se crea un bucle para seguir probando las posiciones.
continuar = "s"
while continuar == "s":

    print("\n¿Desde dónde colocas la esfera?")
    a = int(input("Ingresa la fila (no uses los bordes): "))
    b = int(input("Ingresa la columna (no uses los bordes): "))

    # Calculamos e imprimimos el camino
    camino = caminoProfundidades(matriz, N, M, a, b)
    print("\nEl camino de la esfera fue:")
    print(camino)

    # Preguntamos si quiere seguir
    continuar = input("\n¿Deseas probar otra posición? (s/n): ")

print("\nHasta luego!")



Writing G10_ProfundidadPrincipal.py


In [5]:
%run G10_ProfundidadPrincipal.py

Ingresa el número de filas N (6-10): 6
Ingresa el número de columnas M (6-10): 6

Matriz generada:
[0 0 0 0 0 0]
[  0  56 118  37  22   0]
[  0  36  33 116  33   0]
[ 0 47 59 88 33  0]
[  0  53  83 100  61   0]
[0 0 0 0 0 0]

¿Desde dónde colocas la esfera?
Ingresa la fila (no uses los bordes): 2
Ingresa la columna (no uses los bordes): 2

El camino de la esfera fue:
[[2, 2], [1, 2]]

¿Deseas probar otra posición? (s/n): n

Hasta luego!
